services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=nico
      - POSTGRES_PASSWORD=example123
      - POSTGRES_DB=file-uploader
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: